[build]
  # The command that should be run to build your site
  command = "npm run build"

  # The directory that contains the built files for your site
  publish = ".next"

  # Set the environment variable for Next.js
  environment = { NODE_ENV = "production" }

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true
